name: lint, test, build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
        if: always()
      - name: build:prod project
        run: npm run build:prod
        if: always()
      - name: lint ts
        run: npm run lint:ts
      - name: lint css
        run: npm run lint:scss
        if: always()
      - name: unit test
        run: npm run test:unit
